turn pip-audit into a warning
Signed-off-by: Jose Borreguero <borreguero@gmail.com>

diff --git a/.github/workflows/test_and_deploy.yml b/.github/workflows/test_and_deploy.yml
--- a/.github/workflows/test_and_deploy.yml
+++ b/.github/workflows/test_and_deploy.yml
@@ -55,8 +55,12 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
 
       - name: Dependency check
+        continue-on-error: true
         run: |
-          pixi run audit-deps
+          if ! pixi run audit-deps; then
+            echo "::warning::Dependency check failed"
+            exit 1
+          fi
 
   ##############################
   ### Package and Deployment ###
